# Generated by Django 5.2.12 on 2026-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_faculty_alter_attendancerecord_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
