# Generated by Django 5.2.12 on 2026-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_student_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="attendance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="attendance_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="department_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="semester",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
