# Generated by Django 5.2.12 on 2026-03-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_timetableentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="qr_mode",
            field=models.CharField(
                choices=[("permanent", "Permanent QR"), ("daily", "Daily QR")],
                default="permanent",
                max_length=16,
            ),
        ),
    ]
