# Generated by Django 5.2.12 on 2026-03-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_create_son_user"),
        ("attendance", "0008_add_endtime_duration_sessioncode"),
    ]

    operations = []
