from django.urls import path

from . import views

app_name = "attendance"

urlpatterns = [
    path("", views.ui_home, name="home"),
    path("login", views.ui_login, name="frontend_login"),
    path("login/", views.ui_login, name="frontend_login_slash"),
    path("login/panel/", views.ui_login_panel, name="live_login_panel"),
    path("login/submit/", views.ui_login_submit, name="live_login_submit"),
    path("dashboard", views.ui_faculty, name="frontend_dashboard_noslash"),
    path("dashboard/", views.ui_faculty, name="dashboard"),
    path("student", views.ui_student, name="frontend_student"),
    path("student/", views.ui_student, name="frontend_student_slash"),
    path("admin-dashboard", views.ui_admin, name="frontend_admin_dashboard"),
    path("admin-dashboard/", views.ui_admin, name="frontend_admin_dashboard_slash"),
    path("session/<str:code>", views.ui_session, name="frontend_session"),
    path("session/<str:code>/", views.ui_session, name="frontend_session_slash"),
    path("ui/", views.ui_home, name="ui_home"),
    path("ui/login/", views.ui_login, name="ui_login"),
    path("ui/login/panel/", views.ui_login_panel, name="ui_login_panel"),
    path("ui/login/submit/", views.ui_login_submit, name="ui_login_submit"),
    path("ui/admin/", views.ui_admin, name="ui_admin"),
    path("ui/faculty/", views.ui_faculty, name="ui_faculty"),
    path("ui/student/", views.ui_student, name="ui_student"),
    path("ui/session/<str:code>/", views.ui_session, name="ui_session"),
    path("students/", views.student_list, name="student_list"),
    path("students/register/", views.student_register, name="student_register"),
    path("students/login/", views.student_login, name="student_login"),
    path("students/logout/", views.student_logout, name="student_logout"),
    path("students/me/", views.student_dashboard, name="student_dashboard"),
    path("students/qr/", views.student_qr, name="student_qr"),
    path("students/<int:student_id>/edit/", views.student_edit, name="student_edit"),
    path("students/<int:student_id>/mark/", views.mark_attendance_manual, name="mark_attendance_manual"),
    path("faculty/register/", views.faculty_register, name="faculty_register"),
    path("register/partial/", views.register_partial, name="register_partial"),
    path("api/login/", views.api_login, name="api_login"),
    path("api/logout/", views.api_logout, name="api_logout"),
    path("api/csrf/", views.api_csrf, name="api_csrf"),
    path("api/user/", views.api_user, name="api_user"),
    path("api/student/qr-image/", views.api_student_qr_image, name="api_student_qr_image"),
    path("api/student/enroll-face/", views.api_student_enroll_face, name="api_student_enroll_face"),
    path("api/public/stats/", views.api_public_stats, name="api_public_stats"),
    path("api/dashboard/faculty/overview/", views.api_faculty_dashboard_overview, name="api_faculty_dashboard_overview"),
    path("api/dashboard/student/overview/", views.api_student_dashboard_overview, name="api_student_dashboard_overview"),
    path("api/dashboard/admin/overview/", views.api_admin_dashboard_overview, name="api_admin_dashboard_overview"),
    path("api/professor/sessions/", views.api_professor_sessions, name="api_professor_sessions"),
    path(
        "api/professor/sessions/create/",
        views.api_professor_sessions_create,
        name="api_professor_sessions_create",
    ),
    path(
        "api/professor/sessions/<int:pk>/deactivate/",
        views.api_professor_session_deactivate,
        name="api_professor_session_deactivate",
    ),
    path("api/admin/timetable/", views.api_admin_timetable, name="api_admin_timetable"),
    path("api/admin/timetable/upload/", views.api_admin_timetable_upload, name="api_admin_timetable_upload"),
    path("api/admin/timetable/<int:pk>/", views.api_admin_timetable_detail, name="api_admin_timetable_detail"),
    path("api/admin/students/", views.api_admin_students, name="api_admin_students"),
    path("api/admin/students/clear/", views.api_admin_students_clear, name="api_admin_students_clear"),
    path("api/admin/students/<int:pk>/", views.api_admin_student_detail, name="api_admin_student_detail"),
    path("api/admin/faculty/", views.api_admin_faculty, name="api_admin_faculty"),
    path("api/admin/faculty/<int:pk>/", views.api_admin_faculty_detail, name="api_admin_faculty_detail"),
    path("api/sessions/<str:code>/", views.api_session_detail, name="api_session_detail"),
    path("api/sessions/<str:code>/mark/", views.api_session_mark, name="api_session_mark"),
    path("login/partial/", views.login_partial, name="login_partial"),
    path("login/professor/", views.professor_login, name="professor_login"),
    path("scan/qr/", views.scan_qr_attendance, name="scan_qr"),
    path("scan/qr/frame/", views.scan_qr_frame, name="scan_qr_frame"),
    path("scan/face/", views.scan_face_attendance, name="scan_face"),
    path("scan/face/frame/", views.scan_face_frame, name="scan_face_frame"),
    path("history/", views.attendance_history, name="attendance_history"),
    path("history/export/csv/", views.export_attendance_csv, name="export_attendance_csv"),
    path("attendance/session/create/", views.create_session, name="create_session"),
    path("attendance/session/<str:code>/", views.student_session, name="student_session"),
    path("attendance/session/<str:code>/mark/", views.mark_dual_attendance, name="mark_dual_attendance"),
    path("attendance/professor/", views.professor_dashboard, name="professor_dashboard"),
    path("attendance/session/<str:code>/end/", views.deactivate_session, name="deactivate_session"),
    path("history/export/pdf/", views.export_attendance_pdf, name="export_attendance_pdf"),
    path("encodings/rebuild/", views.rebuild_face_encodings, name="rebuild_face_encodings"),
]
